# Generated by Django 3.0.8 on 2020-07-26 21:26

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadnum', models.IntegerField()),
                ('pickupnum', models.IntegerField()),
                ('deliverynum', models.IntegerField()),
                ('pickuptime', models.DateTimeField()),
                ('deliverytime', models.DateTimeField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('miles', models.IntegerField()),
                ('pickuploc', models.CharField(max_length=100)),
                ('deliveryloc', models.CharField(max_length=100)),
                ('droppick', models.BooleanField(default=False)),
                ('dropdel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trailertype', models.CharField(max_length=100)),
                ('trailernum', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('Phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('trucknum', models.IntegerField()),
                ('drivernum', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='providence_app.Load')),
                ('truckinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='providence_app.Truck')),
            ],
        ),
    ]
